name: docker

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: cfpb/actions/docker-build-push@1be1a44a38e05b7092c844511a0d214e93b43c21
        with:
          image-name: s3-proxy
          token: ${{ secrets.GITHUB_TOKEN }}
