name: docker

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: cfpb/actions/docker-build-push@f584bc1041a1c0590d35533f4f3478ad1229f210
        with:
          image-name: s3-proxy
